primary:
  persistence:
    enabled: true
    existingClaim: "pg-claim"
  initdb:
    scripts:
      sayHello.sh: |
        echo "Starting new DB scripts"
      sayGoodbye.sh: |
        echo "Starting new DB scripts done"

