kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-claim
  namespace: postgres
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
